<a href="https://colab.research.google.com/github/srknplt/Introduction_To_Machine_Learning/blob/main/Numpy_UltraQuickTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 

In [ ]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [ ]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [ ]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [ ]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[70 53 69 84 82 67]


In [ ]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 

[0.77763652 0.00303    0.15512005 0.2238759  0.34506348 0.02206537]


In [ ]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.77763652 2.00303    2.15512005 2.2238759  2.34506348 2.02206537]


In [ ]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[210 159 207 252 246 201]


In [ ]:
feature = np.arange(6, 21)
print(feature)
label = (feature * 3) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [ ]:
noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise 
print(label)

[ 0.28988701 -1.92644232 -1.34283775 -1.31957948  0.34350655 -0.00197676
 -0.95919311  1.39350126 -0.76738158  0.26878205 -0.79800229 -0.82214608
  1.32844456  1.74418169  1.30671745]
[22.28988701 23.07355768 26.65716225 29.68042052 34.34350655 36.99802324
 39.04080689 44.39350126 45.23261842 49.26878205 51.20199771 54.17785392
 59.32844456 62.74418169 65.30671745]
